FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps && npx playwright install --with-deps chromium

COPY . .

EXPOSE 9090

ENV VITE_PORT=9090

CMD ["npm", "run", "dev", "--", "--host"]
