-- Add join_code as nullable so existing tenant rows stay NULL (multiple NULLs allowed in MySQL UNIQUE indexes).
-- New tenants will always receive a code generated by the application layer.
ALTER TABLE tenants
    ADD COLUMN join_code VARCHAR(12) NULL AFTER name,
    ADD UNIQUE KEY uq_tenants_join_code (join_code);

-- Give the seeded default tenant a stable code.
UPDATE tenants SET join_code = 'DEFAULT-0001' WHERE id = '00000000-0000-0000-0000-000000000001';
