# Create .agents directory if it doesn't exist
If (!(Test-Path -Path "C:\projects\freightclub\.agents")) {
    New-Item -ItemType Directory -Path "C:\projects\freightclub\.agents" -Force
}

# Write header to AGENTS.md
$agentsMdPath = "C:\projects\freightclub\.agents\AGENTS.md"
$header = @"
# Resilience Logistics Platform: Agent Rules
*This file is auto-generated by scripts/sync-agents-rules.ps1. Do not edit directly.*

"@
$header | Out-File -FilePath $agentsMdPath -Encoding utf8 -Force

# Read and append .clauderules
If (Test-Path -Path "C:\projects\freightclub\.clauderules") {
    $content = Get-Content -Path "C:\projects\freightclub\.clauderules" -Raw
    "`n## System Rules (from .clauderules)`n" | Out-File -FilePath $agentsMdPath -Encoding utf8 -Append
    $content | Out-File -FilePath $agentsMdPath -Encoding utf8 -Append
}

# Read and append each rule in .claude/rules/*.md
If (Test-Path -Path "C:\projects\freightclub\.claude\rules") {
    $ruleFiles = Get-ChildItem -Path "C:\projects\freightclub\.claude\rules\*.md"
    foreach ($file in $ruleFiles) {
        $ruleName = $file.BaseName -replace "-", " "
        "`n## Rule: $ruleName`n" | Out-File -FilePath $agentsMdPath -Encoding utf8 -Append
        $content = Get-Content -Path $file.FullName -Raw
        $content | Out-File -FilePath $agentsMdPath -Encoding utf8 -Append
    }
}
Write-Output "Successfully generated .agents/AGENTS.md"
